name: tp_docker_films

services:
  read:
    build: ./read
    container_name: read
    restart: always
    ports:
      - 5001:5001
    networks:
      - app_network
    volumes:
      - movies:/app/data
      - utils:/app/utils
      - exceptions:/app/exceptions

  write:
    depends_on:
      - read
    build: ./write
    container_name: write
    restart: always
    ports:
      - 5002:5002
    networks:
      - app_network
    volumes:
      - movies:/app/data
      - utils:/app/utils
      - exceptions:/app/exceptions

volumes:
  movies:
  utils:
  exceptions:

networks:
  app_network: